-- AlterTable
ALTER TABLE "Attendance" ALTER COLUMN "date" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Fee" ALTER COLUMN "amountDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "amountDate" SET DATA TYPE DATE,
ALTER COLUMN "admissionDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "admissionDate" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "Student" ALTER COLUMN "dateOfBirth" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "dateOfBirth" SET DATA TYPE DATE;
